##############################################################################################
##
## Note: See the up.ps1 file for information about the ConnectionStrings__Default variable.
##
##############################################################################################

version: '3'

services:

  abp_host:
    image: abp/mvc
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
    # ConnectionStrings__Default: "${App_DB_ConnStr}"
      TZ: "America/Toronto"
      Kestrel__Endpoints__Http__Url: "http://+:80"
    ports:
      - "44312:80"
    volumes:
      - "./Mvc-Logs:/app/App_Data/Logs"
    restart: always
